"""empty message

Revision ID: cb988e5a6000
Revises: 
Create Date: 2018-12-04 13:25:34.513554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb988e5a6000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('telephone', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('telephone')
    )
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=True)
    op.create_index(op.f('ix_doctors_surname'), 'doctors', ['surname'], unique=True)
    op.create_index(op.f('ix_doctors_telephone'), 'doctors', ['telephone'], unique=False)
    op.create_table('expert_login',
    sa.Column('expertid', sa.String(length=6), nullable=False),
    sa.Column('expertpassword', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('expertid')
    )
    op.create_table('list',
    sa.Column('issue', sa.String(length=40), nullable=False),
    sa.Column('solution', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('issue')
    )
    op.create_index(op.f('ix_list_issue'), 'list', ['issue'], unique=False)
    op.create_index(op.f('ix_list_solution'), 'list', ['solution'], unique=True)
    op.create_table('student_login',
    sa.Column('studentid', sa.String(length=6), nullable=False),
    sa.Column('studentpassword', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('studentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_login')
    op.drop_index(op.f('ix_list_solution'), table_name='list')
    op.drop_index(op.f('ix_list_issue'), table_name='list')
    op.drop_table('list')
    op.drop_table('expert_login')
    op.drop_index(op.f('ix_doctors_telephone'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_surname'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
